#!/bin/bash
# is this fun?

case $1 in

creation)
	cat <<EOF
When, long ago, the gods created Earth
In Jove’s fair image Man was shaped at birth.
The beasts for lesser parts were next designed;
Yet were they too remote from humankind.
To fill the gap, and join the rest to Man,
Tåh’Olympian host conceiv’d a clever plan.
A beast they wrought, in semi-human figure,
Filled it with vice, and called the thing a Nigger.
EOF
	;;
city)
	cat <<EOF
 It was golden and splendid,
That City of light;
A vision suspended
In deeps of the night;
A region of wonder and glory, whose temples were marble and white.

I remember the season
It dawn’d on my gaze;
The mad time of unreason,
The brain-numbing days
When Winter, white-sheeted and ghastly, stalks onward to torture and craze.

More lovely than Zion
It shone in the sky,
When the beams of Orion
Beclouded my eye,
Bringing sleep that was fill’d with dim mem’ries of moments obscure and gone by.

Its mansions were stately
With carvings made fair,
Each rising sedately
On terraces rare,
And the gardens were fragrant and bright with strange miracles blossoming there.

The avenues lur’d me
With vistas sublime;
Tall arches assur’d me
That once on a time
I had wander’d in rapture beneath them, and bask’d in the Halcyon clime.

On the plazas were standing
A sculptur’d array;
Long-bearded, commanding,
Grave men in their day—
But one stood dismantled and broken, its bearded face batter’d away.

In that city effulgent
No mortal I saw;
But my fancy, indulgent
To memory’s law,
Linger’d long on the forms in the plazas, and eyed their stone features with awe.

I fann’d the faint ember
That glow’d in my mind,
And strove to remember
The aeons behind;
To rove thro’ infinity freely, and visit the past unconfin’d.

Then the horrible warning
Upon my soul sped
Like the ominous morning
That rises in red,
And in panic I flew from the knowledge of terrors forgotten and dead. 
EOF
	;;
forest)
	cat <<EOF
They cut it down, and where the pitch-black aisles
 Of forest night had hid eternal things,
They scal’d the sky with tow’rs and marble piles
 To make a city for their revellings.

White and amazing to the lands around
 That wondrous wealth of domes and turrets rose;
Crystal and ivory, sublimely crown’d
 With pinnacles that bore unmelting snows.

And through its halls the pipe and sistrum rang,
 While wine and riot brought their scarlet stains;
Never a voice of elder marvels sang,
 Nor any eye call’d up the hills and plains.

Thus down the years, till on one purple night
 A drunken minstrel in his careless verse
Spoke the vile words that should not see the light,
 And stirr’d the shadows of an ancient curse.

Forests may fall, but not the dusk they shield;
 So on the spot where that proud city stood,
The shuddering dawn no single stone reveal’d,
 But fled the blackness of a primal wood.
EOF
	;;
antarktos)
	cat <<EOF
Deep in my dream the great bird whispered queerly
Of the black cone amid the polar waste;
Pushing above the ice-sheet lone and drearly,
By storm-crazed aeons battered and defaced.
Hither no living earth-shapes take their courses,
And only pale auroras and faint suns
Glow on that pitted rock, whose primal sources
Are guessed at dimly by the Elder Ones.

If men should glimpse it, they would merely wonder
What tricky mound of Nature’s build they spied;
But the bird told of vaster parts, that under
The mile-deep ice-shroud crouch and brood and bide.
God help the dreamer whose mad visions shew
Those dead eyes set in crystal gulfs below!
EOF
	;;
window)
	cat <<EOF
The house was old, with tangled wings outthrown,
Of which no one could ever half keep track,
And in a small room somewhat near the back
Was an odd window sealed with ancient stone.
There, in a dream-plagued childhood, quite alone
I used to go, where night reigned vague and black;
Parting the cobwebs with a curious lack
Of fear, and with a wonder each time grown.

One later day I brought the masons there
To find what view my dim forbears had shunned,
But as they pierced the stone, a rush of air
Burst from the alien voids that yawned beyond.
They fled—but I peered through and found unrolled
All the wild worlds of which my dreams had told.
EOF
	;;
nyarlathotep)
	cat <<EOF
And at the last from inner Egypt came
The strange dark One to whom the fellahs bowed;
Silent and lean and cryptically proud,
And wrapped in fabrics red as sunset flame.
Throngs pressed around, frantic for his commands,
But leaving, could not tell what they had heard;
While through the nations spread the awestruck word
That wild beasts followed him and licked his hands.

Soon from the sea a noxious birth began;
Forgotten lands with weedy spires of gold;
The ground was cleft, and mad auroras rolled
Down on the quaking citadels of man.
Then, crushing what he chanced to mould in play,
The idiot Chaos blew Earth’s dust away.
EOF
	;;
*) cat <<EOF ;;
Dodaj tytuł jako argument, np. 
> hpl forest

obecnie dodane wiersze:
    antarktos [Fungi from Yuggoth XV: Antarktos]
    city [The City]
    forest [The Forest]
    nyarlathothep [Fungi from Yuggoth XXI: Nyarlathotep]
    window [Fungi from Yuggoth XVI: The Window]
EOF
esac
