#! /bin/bash

set -euo pipefail

if [ $# != 1 ]; then
	echo "podaj plik .md do wyświetlenia"
	exit 1
fi

if [[ "${1##*.}" == "pdf" ]]; then
	zathura "$1" &
else
	pandoc --pdf-engine=xelatex -V lang=pl -V mainfont="DejaVu Serif" -t pdf "$1" | zathura - &
fi
